### ISSUE TITLE
読み上げとの連携

### ISSUE THREAD

**Issue by Y-RyuZU** [AzisabaNetwork/RyuZUPluginChat#12]
RyuZUPluginChatのconfigに
  Bot:
    Voice:
      Token: token
      ChannelID: 868782148004503553
      LunaChatChannelName: voicechat
追加
・指定したLunaChatChannelで送信されたメッセージを指定したチャンネルに送る
・「/vc message」で送信されたメッセージを指定したチャンネルに送る
・Botが送信するメッセージは送ったメッセージのみ、プレイヤー名やPrefixは送信しない
・指定したLunaChatChannelに/vcの時はプレイヤー名、Prefix込みのメッセージを送信
・用途は読み上げとの同期

**Comment by siloneco** [comment]
送った直後にメッセージ編集して、送信者名表示するようにしたら面白いかも

**Comment by siloneco** [comment]
てかこれWebhookでよくない？

**Comment by siloneco** [comment]
Discordに送られた内容を鯖内に表示したいので、Botを利用する方針で行く

**Comment by siloneco** [comment]
- [ ] Configに設定項目を追加
- [ ] voicechat chの内容をDiscordに転送
- [ ] Discordの内容をvoicechat chに転送
- [ ] /vc 実装
- [ ] 荒らし対策のためクールタイム追加
- [ ] 荒らし対策のためメンション除外 ( @ を全角に変更 )
- [ ] Discordのメッセージをすぐに編集して送信者を表示
- [ ] LunaChatチャンネル参加プレイヤー同期

**Comment by siloneco** [comment]
最後の `LunaChat チャンネル参加プレイヤー同期` はタスクが重そうなので #19 に移動
