### ISSUE TITLE
Translation?

### ISSUE THREAD

**Issue by Folas1337** [AzisabaNetwork/RyuZUPluginChat#134]
Can we please get an option to translate the plugin messages? <3

I'm loving the Redis functionality and I really want to use this on my server but without the ability to translate it, it's going to be difficult to use :(

**Comment by Y-RyuZU** [comment]
Thank you for your request. I will cosider translating this plugin in English

**Comment by Folas1337** [comment]
I'd even love to help if necessary :) Otherwise, thank you so much <3
