### ISSUE TITLE
PAPI support

### ISSUE THREAD

**Issue by Folas1337** [AzisabaNetwork/RyuZUPluginChat#135]
Another suggestion/feature request of mine, I'd love to see PlaceholderAPI support as almost all plugins support it 😄
So I can have any placeholder in my global messages, not just the pre defined ones.

**Comment by siloneco** [comment]
Thank you for your suggestion, but currently we don't have a plan to add PAPI support. We made this plugin for using in our server, so we just don't need to support PAPI.

This issue will be re-opened if we decide to support PAPI in the future.
