### ISSUE TITLE
/rpc tell message gets sent even when I /hide <user>

### ISSUE THREAD

**Issue by Folas1337** [AzisabaNetwork/RyuZUPluginChat#140]
If I use "/hide <userA>" and then userA sends me a message with "/rpc tell Folas1337 Hi" it still shows that message even though it shouldn't.
![image](https://user-images.githubusercontent.com/39222968/195939939-57daf87f-8c44-4f89-b476-6d7f8f02cee5.png)

Also there seems to be no way of disabling "/rpc tell" or just "/tell" in general, I'd love that to be a thing as well as I have another plugin handling it.

**Comment by siloneco** [comment]
Does the problem persist after a sufficient amount of time (30 seconds or so)? Also, I'd like to see if there are any errors in the console.

**Comment by Folas1337** [comment]
Yeah, I have waited over a minute now after hiding them, making sure they are in the hidelist as well:
![image](https://user-images.githubusercontent.com/39222968/195983043-2046cc2c-5774-495e-8201-877bac157c96.png)

The console says nothing out of the ordinary either:
```
[11:02:56] [pool-19-thread-1/INFO]: [RyuZUPluginChat] [Private-Chat] Fal_Hayden(mc1-test1) -> Folas1337(mc1-test1) >> Hi 
[11:02:56] [pool-19-thread-1/INFO]: [RyuZUPluginChat] [Private-Chat(Debug)] Sending 'Fal_Hayden to Folas1337' private chat to: Fal_Hayden
```

If you need any other information let me know.

**Comment by Folas1337** [comment]
I don't need this issue anymore and it seems like you also don't since there hasn't been a response for a long time, so I'll just close it here as I've moved on to another plugin.
Have a good day :)
