### ISSUE TITLE
/ch <channel> <msg> gets processed even when "lunachat.speak.<channel>" permission is revoked

### ISSUE THREAD

**Issue by Folas1337** [AzisabaNetwork/RyuZUPluginChat#141]
With just LunaChat installed I can not speak in a certain channel by using "/ch \<channel\> \<msg\>" as I revoked the permission "lunachat.speak.<channel>" but as soon as I install RyuZUPluginChat it gets processed.

The user who doesn't have access can't see he sent it successfully but people who are inside the channel can see the message. It should have been cancelled instead though.

It seems this plugin doesn't respect the permission properly

**Comment by siloneco** [comment]
Fixed in [version 4.0.1](https://github.com/AzisabaNetwork/RyuZUPluginChat/releases/tag/v4.0.1). Thanks for the report.
