### ISSUE TITLE
/stop時の処理が固まる可能性

### ISSUE THREAD

**Issue by siloneco** [AzisabaNetwork/RyuZUPluginChat#59]
Diverseでサーバー停止が正常にできないバグを確認済み。Discordと連携したテスト鯖では同様の症状が確認できないので、他のPLのバグの可能性もあるけど、RPCの可能性が高い

**Comment by siloneco** [comment]
@acrylic-style 終了時の処理周りを確認してほしい
具体的に止まりそうな箇所としては
* RyuZUPluginChat.newChain()... しているブロック内の処理が一生終わっていない場合止まる (asyncでも)
* onDisable() 内の処理が一生終わらない場合止まる
くらいしか思い浮かばない

**Comment by siloneco** [comment]
サーバー停止と同時にプレイヤー退出するから、QuitEvent内のTaskChainで止まってる説はあるかなぁ

**Comment by acrylic-style** [comment]
jstackでスレッドダンプを出せば問題が絞れると思われる

**Comment by siloneco** [comment]
スレッドダンプ取ったところRPCは無関係の可能性が高いのでクローズします
