### ISSUE TITLE
%usernameにニックネームが反映されない

### ISSUE THREAD

**Issue by acrylic-style** [AzisabaNetwork/RyuZUPluginChat#62]
LunaChatのformatに`%username`を入れると(expected)Essentialsで設定した`/nick`ではなく(actual)普通のプレイヤー名が出てくる
LunaChatのみの場合は`%username`でニックネームが反映される

**Comment by siloneco** [comment]
もしかして `%displayname` って存在しない...? 存在するとしたら`%displayname`には何が入るんだろう

**Comment by siloneco** [comment]
とりあえず同じもの入れるか
